appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a7d1578b0700305baa
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: E5gwowf7Tp86kV97xV1aX1MOqGZ8NAo6hu/YnGzVNxw/cINERIrhOvaBwLM0eq2ZmQ9NaKhzrgM45nP6FjjZcWCkcW0HXKVUTlgNjWxkccHFmP/Xqgb+LKmoJw9a+RrVsDdMFsKKVL2Apae08f/12eoTzDa6+961B6WEm4kdeU2Q3k9c92W2wD3dE2tBCmfrZc3Ocqq7w5HCCTikO/oAuYoMSTNdMaVyoQWIK7lfKPALkHQYVdZ8ksi/gPW4LZZC5tW5CN3NkQ0UX7kinLWxtmbn7Nk6eezEXi+Pr61nm0b7QYpHhcqwPrfq4j2MmdwoMo6fp8TNCRz1jWrdpXM5kwsox1WNKjPLEJPhdsK7KAChlecanhaJkybM/ajuiyXOKHuESUjskW6dI5mTlBmh7M1QAShXSxAX0B5UHCd2fWcVlzIfMnc8krnLtzv90pusMsVJSu45DyJuil3JkoNtcIEWpu0sLHOAGbPzfEF5ragJDbdmbLMOpsG68FamLpalrAsL0m7qlHGHmdr6JGdVHB2akuhvlvHZ+NlfyRnNx5IJ7EfjRs/gYjrBnj9RkATNcdFVY0qxdWIJFdb49PVM0dmyrwN1ntyFa53CrNdByrWWOkZfIBxaZjfU2CfdBYn5z/7RNviQ9mouhJTi5Mpu6gy56tvAP+GGVS+hMNxv24c=}
